import { prisma } from "./shared"

export async function resetDatabase() {
  await prisma.leadFeedback.deleteMany()
  await prisma.serviceLead.deleteMany()
  await prisma.intentInsight.deleteMany()
  await prisma.userActionEvent.deleteMany()
  await prisma.riskFocusItem.deleteMany()
  await prisma.doctorHealthProfile.deleteMany()
  await prisma.qualityIssue.deleteMany()
  await prisma.agentFeedback.deleteMany()
  await prisma.agentStep.deleteMany()
  await prisma.agentRun.deleteMany()
  await prisma.guidePlan.deleteMany()
  await prisma.recommendation.deleteMany()
  await prisma.triageResult.deleteMany()
  await prisma.preConsultReport.deleteMany()
  await prisma.preConsultMessage.deleteMany()
  await prisma.preConsultSession.deleteMany()
  await prisma.promptTemplate.deleteMany()
  await prisma.modelVersion.deleteMany()
  await prisma.knowledgeChunk.deleteMany()
  await prisma.knowledgeDocument.deleteMany()
  await prisma.matchingRule.deleteMany()
  await prisma.departmentMappingRule.deleteMany()
  await prisma.triageRule.deleteMany()
  await prisma.healthTask.deleteMany()
  await prisma.healthSummary.deleteMany()
  await prisma.allergy.deleteMany()
  await prisma.labResult.deleteMany()
  await prisma.medication.deleteMany()
  await prisma.diagnosis.deleteMany()
  await prisma.medicalRecord.deleteMany()
  await prisma.healthTag.deleteMany()
  await prisma.adminProfile.deleteMany()
  await prisma.doctorProfile.deleteMany()
  await prisma.residentProfile.deleteMany()
  await prisma.expertPool.deleteMany()
  await prisma.serviceCapability.deleteMany()
  await prisma.doctor.deleteMany()
  await prisma.department.deleteMany()
  await prisma.institution.deleteMany()
  await prisma.user.deleteMany()
}
